#Generated by exporting
import Sprites as s, Realms

#Sprites
r = Realms.Realm('0')

#
sp = s.AnimatedMagicalCreatureSprite('ShopKeep', 756, 720)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('NPC_HPD', 514, 273)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('NPC_HP', 518, 274)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('GoblinR', 451, 308)
sp.moveMode = 'RandomWalk'
sp.setMovementSpeed(15)
r.gameSprites.add(sp)
r.enemies.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('DemonL', 707, 293)
sp.moveMode = 'RandomWalk'
sp.setMovementSpeed(15)
r.gameSprites.add(sp)
r.enemies.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('GhostDeath', 523, 290)
sp.moveMode = 'RandomWalk'
sp.setMovementSpeed(15)
r.gameSprites.add(sp)
r.enemies.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('Fountain', 164, 103)
r.gameSprites.add(sp)
r.allyFountains.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('RedFountain', 200, 200)
r.gameSprites.add(sp)
r.enemyFountains.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('HPOT', 820, 773)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('MPOT', 697, 786)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('Chest', 834, 479)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('Spike', 380, 420)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('SSafer', 260, 420)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA1', 52, 233)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA2', 339, -612)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA3', -1431, -831)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA4', 766, -1153)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA5', 235, -775)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA6', -559, 544)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA7', 501, -373)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA8', 1198, 588)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA9', -1044, -1657)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA10', -1166, -664)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA11', 1401, -1084)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA12', -3034, -41)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA13', -3034, -41)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('HWA6A', 501, -575)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA2AB', 400, 1673)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('HWA4C', -1557, 1581)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('HWA4D', -725, -1216)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('HWA4E', -2517, 862)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('HWA4F', 235, -1376)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('VWA4G', -1557, 1022)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('VWA6H', 271, 713)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('VWA6I', 959, 713)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('VWA2J', 1060, -575)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('VWA2K', 1060, -575)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('PInvt', 493, 1136)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('PSkill', 468, 786)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('ExpP', 437, 576)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('Life', 438, 594)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('ManaP', 435, 618)
r.gameSprites.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('Player1', -1777, -297)
sp.meleeDamage = 2
r.gameSprites.add(sp)
r.allies.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('Player1', 503, 416)
sp.meleeDamage = 2
r.gameSprites.add(sp)
r.allies.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA3', -1111, -109)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA3', -49, 46)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA3', -37, 398)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedMagicalCreatureSprite('WA3', -1419, -479)
r.gameSprites.add(sp)
r.Walls.add(sp)
