#Generated by exporting
import Sprites as s, Realms

#Sprites
r = Realms.Realm('0')

#
sp = s.MagicalCreature('GoblinR', 160, 520)
r.gameSprites.add(sp)
r.enemies.add(sp)
#
sp = s.MagicalCreature('DemonL', 200, 720)
r.gameSprites.add(sp)
r.enemies.add(sp)
#
sp = s.Fountain('Fountain', 800, 800)
r.gameSprites.add(sp)
r.Fountains.add(sp)
#
sp = s.AnimatedSprite('HPOT', 500, 500)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('MPOT', 500, 700)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('Chest', 200, 300)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('Spike', 700, 600)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('SSafer', 1000, 1000)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('Wall', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 240, 121)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 160, 0)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 240, 57)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 320, 0)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 400, 0)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 480, 0)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 560, 0)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 640, 0)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('Wall', 720, 0)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WallCL', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WallCR', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WallCLR', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WallLR', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallLR', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallR', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallL', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallFill', 240, 3)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallFill', 160, -40)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallFill', 240, -37)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallFill', 320, -40)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallFill', 400, -40)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallFill', 480, -40)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallFill', 560, -40)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallFill', 640, -40)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallCLTR', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallTop', 240, -37)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallTop', 160, -80)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallTop', 240, -101)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallTop', 320, -80)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallTop', 400, -80)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallTop', 480, -80)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallTop', 560, -80)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallTop', 640, -80)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallCRT', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallCLT', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallCRB', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallCLB', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('BWallCLRB', 80, 81)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA1', -1300, 400)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA2', -840, 201)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA3', -840, -179)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA4', -500, -1200)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA5', -500, -900)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA6', -500, 700)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA7', -200, -200)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA8', -500, -500)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('WA9', -1000, -1000)
r.gameSprites.add(sp)
r.Walls.add(sp)
#
sp = s.AnimatedSprite('PInvt', 1200, 1200)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('PSkill', -700, -700)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('ExpP', 900, 760)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('Life', 900, 800)
r.gameSprites.add(sp)
#
sp = s.AnimatedSprite('ManaP', 920, 820)
r.gameSprites.add(sp)
#
sp = s.MagicalCreature('Player1', 115, 130)
sp.meleeDamage = 2
r.gameSprites.add(sp)
r.allies.add(sp)
